[server]
headless = true
enableXsrfProtection = true
enableCORS = true
maxUploadSize = 2

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"

[theme]
base = "light"
primaryColor = "#12736D"
backgroundColor = "#F6F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B3A"
font = "sans serif"
